### PR TITLE
This will fix links that are broken if people block google analytics tracking

### LINKED ISSUE #62: the links..they do nothing!
Chrome Version 49.0.2623.110 (64-bit) / Mac

Clicking "View Library on Github" [here](https://tessel.io/modules#module-climate) doesn't do anything for me.

### PR DESCRIPTION
**Pull request by reconbot**
Or if google takes longer that 300ms to respond
Closes #62

### CODE REVIEW

File: public/tracking/event_track.js [hunk 1]
```diff
@@ -8,6 +8,12 @@ if (typeof jQuery != 'undefined') {
         var el = jQuery(this);
         var track = true;
         var href = (typeof(el.attr('href')) != 'undefined' ) ? el.attr('href') : '';
+        // if tracking fails just goto the link after 300ms
+        if (href) {
+          setTimeout(function(){
+            window.location.href = href;
+          }, 300);
+        }
```
Comment (rwaldron) [inline public/tracking/event_track.js:16]: 0_o

Wacky.

Comment (reconbot) [inline public/tracking/event_track.js:16]: The function relied on google existing, and always returning in a
reasonable time

On Thu, Apr 21, 2016 at 4:49 PM, Rick Waldron notifications@github.com
wrote:

> In public/tracking/event_track.js
> https://github.com/tessel/tessel.io/pull/69#discussion_r60652782:
> 
> > @@ -8,6 +8,12 @@ if (typeof jQuery != 'undefined') {
> >          var el = jQuery(this);
> >          var track = true;
> >          var href = (typeof(el.attr('href')) != 'undefined' ) ? el.attr('href') : '';
> > -        // if tracking fails just goto the link after 300ms
> > -        if (href) {
> > -          setTimeout(function(){
> > -            window.location.href = href;
> > -          }, 300);
> > -        }
> 
> 0_o
> 
> Wacky.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/tessel/tessel.io/pull/69/files/54431ec19d3bbf38f731edecd9d4cbdbf8bbf91e#r60652782

## 

Francis Gulotta
Director of Web Connected Devices
Mobile: 917-805-3079

Comment (reconbot) [inline public/tracking/event_track.js:16]: I've written that timeout ... too many times

On Thu, Apr 21, 2016 at 5:10 PM, Francis Gulotta francis@bocoup.com wrote:

> The function relied on google existing, and always returning in a
> reasonable time
> 
> On Thu, Apr 21, 2016 at 4:49 PM, Rick Waldron notifications@github.com
> wrote:
> 
> > In public/tracking/event_track.js
> > https://github.com/tessel/tessel.io/pull/69#discussion_r60652782:
> > 
> > > @@ -8,6 +8,12 @@ if (typeof jQuery != 'undefined') {
> > >          var el = jQuery(this);
> > >          var track = true;
> > >          var href = (typeof(el.attr('href')) != 'undefined' ) ? el.attr('href') : '';
> > > -        // if tracking fails just goto the link after 300ms
> > > -        if (href) {
> > > -          setTimeout(function(){
> > > -            window.location.href = href;
> > > -          }, 300);
> > > -        }
> > 
> > 0_o
> > 
> > Wacky.
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > https://github.com/tessel/tessel.io/pull/69/files/54431ec19d3bbf38f731edecd9d4cbdbf8bbf91e#r60652782
> 
> ## 
> 
> Francis Gulotta
> Director of Web Connected Devices
> Mobile: 917-805-3079

## 

Francis Gulotta
Director of Web Connected Devices
Mobile: 917-805-3079

**Comment by Frijol** [comment]
oh hey this looks mergeable. Ready when you are @reconbot

**Comment by Frijol** [comment]
👍
